// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages/messages.proto

/*
Package messages is a generated protocol buffer package.

It is generated from these files:
	messages/messages.proto

It has these top-level messages:
	PID
	RequestWork
	SubmitWork
	SubmitExpectedResultCount
	SubmitResult
*/
package messages

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PID struct {
	Address string `protobuf:"bytes,1,opt,name=Address" json:"Address,omitempty"`
	Id      string `protobuf:"bytes,2,opt,name=Id" json:"Id,omitempty"`
}

func (m *PID) Reset()                    { *m = PID{} }
func (m *PID) String() string            { return proto.CompactTextString(m) }
func (*PID) ProtoMessage()               {}
func (*PID) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *PID) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *PID) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type RequestWork struct {
	Pid *PID `protobuf:"bytes,1,opt,name=pid" json:"pid,omitempty"`
}

func (m *RequestWork) Reset()                    { *m = RequestWork{} }
func (m *RequestWork) String() string            { return proto.CompactTextString(m) }
func (*RequestWork) ProtoMessage()               {}
func (*RequestWork) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *RequestWork) GetPid() *PID {
	if m != nil {
		return m.Pid
	}
	return nil
}

type SubmitWork struct {
	Pid  *PID  `protobuf:"bytes,1,opt,name=pid" json:"pid,omitempty"`
	Data int32 `protobuf:"varint,3,opt,name=data" json:"data,omitempty"`
}

func (m *SubmitWork) Reset()                    { *m = SubmitWork{} }
func (m *SubmitWork) String() string            { return proto.CompactTextString(m) }
func (*SubmitWork) ProtoMessage()               {}
func (*SubmitWork) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *SubmitWork) GetPid() *PID {
	if m != nil {
		return m.Pid
	}
	return nil
}

func (m *SubmitWork) GetData() int32 {
	if m != nil {
		return m.Data
	}
	return 0
}

type SubmitExpectedResultCount struct {
	Count int32 `protobuf:"varint,1,opt,name=count" json:"count,omitempty"`
}

func (m *SubmitExpectedResultCount) Reset()                    { *m = SubmitExpectedResultCount{} }
func (m *SubmitExpectedResultCount) String() string            { return proto.CompactTextString(m) }
func (*SubmitExpectedResultCount) ProtoMessage()               {}
func (*SubmitExpectedResultCount) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *SubmitExpectedResultCount) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type SubmitResult struct {
	Data   int32   `protobuf:"varint,3,opt,name=data" json:"data,omitempty"`
	Result float32 `protobuf:"fixed32,4,opt,name=result" json:"result,omitempty"`
}

func (m *SubmitResult) Reset()                    { *m = SubmitResult{} }
func (m *SubmitResult) String() string            { return proto.CompactTextString(m) }
func (*SubmitResult) ProtoMessage()               {}
func (*SubmitResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *SubmitResult) GetData() int32 {
	if m != nil {
		return m.Data
	}
	return 0
}

func (m *SubmitResult) GetResult() float32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func init() {
	proto.RegisterType((*PID)(nil), "messages.PID")
	proto.RegisterType((*RequestWork)(nil), "messages.RequestWork")
	proto.RegisterType((*SubmitWork)(nil), "messages.SubmitWork")
	proto.RegisterType((*SubmitExpectedResultCount)(nil), "messages.SubmitExpectedResultCount")
	proto.RegisterType((*SubmitResult)(nil), "messages.SubmitResult")
}

func init() { proto.RegisterFile("messages/messages.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 239 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x90, 0x3f, 0x4f, 0xc3, 0x30,
	0x10, 0xc5, 0x15, 0xa7, 0x29, 0x70, 0x05, 0x86, 0x13, 0xa2, 0x86, 0x85, 0xc8, 0x53, 0xa6, 0x54,
	0xc0, 0xc6, 0x16, 0x08, 0x43, 0x06, 0xa4, 0xc8, 0x0c, 0xcc, 0x69, 0x7c, 0x42, 0x15, 0x04, 0x07,
	0xff, 0x91, 0xf8, 0x4c, 0x7c, 0x4a, 0x14, 0xbb, 0x61, 0x62, 0x60, 0x7b, 0x3f, 0xdf, 0xbd, 0xe7,
	0xd3, 0x83, 0xf5, 0x40, 0xd6, 0x76, 0xaf, 0x64, 0x37, 0xb3, 0x28, 0x47, 0xa3, 0x9d, 0xc6, 0xc3,
	0x99, 0xc5, 0x06, 0xd2, 0xb6, 0xa9, 0x91, 0xc3, 0x41, 0xa5, 0x94, 0x21, 0x6b, 0x79, 0x92, 0x27,
	0xc5, 0x91, 0x9c, 0x11, 0x4f, 0x81, 0x35, 0x8a, 0xb3, 0xf0, 0xc8, 0x1a, 0x25, 0x4a, 0x58, 0x49,
	0xfa, 0xf4, 0x64, 0xdd, 0x8b, 0x36, 0x6f, 0x78, 0x05, 0xe9, 0xb8, 0x53, 0xc1, 0xb4, 0xba, 0x39,
	0x29, 0x7f, 0xff, 0x69, 0x9b, 0x5a, 0x4e, 0x13, 0x51, 0x01, 0x3c, 0xfb, 0xed, 0xb0, 0xfb, 0xdf,
	0x3a, 0x22, 0x2c, 0x54, 0xe7, 0x3a, 0x9e, 0xe6, 0x49, 0x91, 0xc9, 0xa0, 0xc5, 0x35, 0x5c, 0xc4,
	0x88, 0xc7, 0xaf, 0x91, 0x7a, 0x47, 0x4a, 0x92, 0xf5, 0xef, 0xee, 0x41, 0xfb, 0x0f, 0x87, 0x67,
	0x90, 0xf5, 0x93, 0x08, 0x99, 0x99, 0x8c, 0x20, 0xee, 0xe0, 0x38, 0x5a, 0xe2, 0xea, 0x5f, 0xb1,
	0x78, 0x0e, 0x4b, 0x13, 0xa6, 0x7c, 0x91, 0x27, 0x05, 0x93, 0x7b, 0xba, 0xbf, 0xfc, 0x66, 0xeb,
	0x76, 0xaa, 0xa9, 0xea, 0x9d, 0x36, 0x35, 0x0d, 0xba, 0x7c, 0xda, 0xdf, 0xb9, 0x5d, 0x86, 0xfe,
	0x6e, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x10, 0x96, 0x01, 0x81, 0x5a, 0x01, 0x00, 0x00,
}
